import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "../components/Products";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>{error.message}</p>;
  const products = data.products.data;

  console.log(products);

  return (
    <div>
      <Head>
        <title>Deb's Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>All Products</h1>
      {products.map((product) => (
        <Products key={product.attributes.slug} product={product} />
      ))}
    </div>
  );
}
