import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "../components/Products";

export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>{error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Deb's Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        id="products-gallery"
        className="grid grid-cols-20 justify-items-center mt-24">
        {products.map((product) => (
          <Products key={product.attributes.slug} product={product} />
        ))}
      </div>
    </div>
  );
}
